import Head from "next/head";
import { useState } from "react";
import Footer from "../components/Footer";
import { NavbarGuest, NavbarUser } from "../components/Navbar";

interface Layout {
  children: React.ReactNode;
  nameTitle: string;
  noFooter?: boolean;
  noNavbar?: boolean;
  userInterface?: boolean;
}

export default function Layout({
  children,
  nameTitle,
  noFooter = false,
  noNavbar = false,
  userInterface = false,
}: Layout) {
  const Footers = noFooter ? null : <Footer />;
  const Navbars = noNavbar ? null : userInterface ? (
    <NavbarUser />
  ) : (
    <NavbarGuest />
  );

  return (
    <div>
      <Head>
        <title>{nameTitle}</title>
        <link
          rel="icon"
          type="image/png"
          href="https://cdn.discordapp.com/attachments/1061967634846978088/1062321083920961606/person-icon.png"
        />
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        {Navbars}
        <div className="min-h-screen p-2">{children}</div>
        {Footers}
      </main>
    </div>
  );
}
