import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import { HeadTitleInterface } from "../interface";

export default function HeadTitle<S extends JSX.Element>({
  component: components,
  nameTitle = "Head",
}: HeadTitleInterface<S>) {
  return (
    <div>
      <Head>
        <title>{nameTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="w-full h-[77vh] py-[6rem]">{components}</div>
        <Footer />
      </main>
    </div>
  );
}
